# Generated by Django 3.2.9 on 2021-11-24 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weather', '0002_alter_city_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favcities', to=settings.AUTH_USER_MODEL),
        ),
    ]
