# Generated by Django 3.2.9 on 2021-12-01 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_alter_city_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='user',
            new_name='owner',
        ),
    ]
