# Generated by Django 3.2.9 on 2021-12-02 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0006_rename_user_city_owner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outfit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.IntegerField(unique=True)),
                ('top', models.CharField(max_length=25)),
                ('bottom', models.CharField(max_length=25)),
                ('outerwear', models.CharField(max_length=25)),
                ('accessories', models.CharField(max_length=25)),
                ('footwear', models.CharField(max_length=25)),
            ],
        ),
    ]
