# Generated by Django 3.2.9 on 2021-12-02 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0009_auto_20211202_1618'),
        ('weather', '0009_auto_20211202_1721'),
    ]

    operations = [
    ]
