# Generated by Django 3.2.9 on 2021-12-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0010_merge_0009_auto_20211202_1618_0009_auto_20211202_1721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outfit',
            name='outerwear',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
